import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    q: "Is CareerPilot AI really free?",
    a: "Yes, 100% free. It runs entirely on your machine using Ollama and open-source AI models. No API keys, no subscriptions, no hidden costs.",
  },
  {
    q: "How does the AI analysis work without an internet connection?",
    a: "CareerPilot uses Ollama to run AI models (like Qwen3) locally on your computer. Your resume data never leaves your machine, making it completely private and offline-capable.",
  },
  {
    q: "What file formats are supported?",
    a: "Currently, CareerPilot accepts PDF resumes. The system extracts text from your PDF and sends it to the local AI for analysis. We recommend clean, text-based PDFs for the best results.",
  },
  {
    q: "How accurate is the ATS score?",
    a: "The ATS score is generated by AI that simulates how Applicant Tracking Systems parse resumes. While it provides excellent directional guidance for improving your resume, actual ATS systems vary between companies.",
  },
  {
    q: "Can I use this for any job role?",
    a: "Absolutely. The AI adapts its analysis and interview questions based on the role you specify — from software engineering to data science, product management, marketing, and more.",
  },
  {
    q: "How does the AI mock interview work?",
    a: "You select a role and difficulty, and the AI generates interview questions. You answer using your microphone (via the browser's built-in Speech-to-Text), and the AI evaluates your communication, technical accuracy, and overall confidence.",
  },
  {
    q: "What AI model do you use?",
    a: "By default, CareerPilot uses Qwen3 through Ollama, but you can configure any Ollama-compatible model. If you have an OpenAI API key, you can also switch to GPT models.",
  },
];

function FAQ() {
  const [openIndex, setOpenIndex] = useState(null);

  return (
    <section className="py-24">
      <div className="max-w-3xl mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <span className="text-xs font-semibold text-blue-400 uppercase tracking-widest">
            FAQ
          </span>
          <h2 className="text-4xl font-extrabold mt-3">
            Frequently Asked Questions
          </h2>
        </motion.div>

        <div className="space-y-3">
          {faqs.map((faq, i) => {
            const isOpen = openIndex === i;
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
                className="glass rounded-xl overflow-hidden"
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : i)}
                  className="w-full flex items-center justify-between px-6 py-4 text-left"
                >
                  <span className="text-sm font-semibold text-white pr-4">
                    {faq.q}
                  </span>
                  <motion.div
                    animate={{ rotate: isOpen ? 180 : 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <ChevronDown
                      size={18}
                      className="text-slate-500 shrink-0"
                    />
                  </motion.div>
                </button>

                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                      className="overflow-hidden"
                    >
                      <p className="px-6 pb-4 text-sm text-slate-400 leading-relaxed">
                        {faq.a}
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

export default FAQ;
